version: '3.7'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jovan
      - POSTGRES_DB=postgres
    ports:
      - "192.168.255.178:5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@mail.com
      - PGADMIN_DEFAULT_PASSWORD=jovan
    ports:
      - "5050:80"
